### ISSUE TITLE
[Doc] add documentation

### ISSUE THREAD

**Issue by ghost** [vayan/ldtk-py#1]
Any chance you could add documentation for each function and class in `api.py`?

I understand you are probably busy and this is a tedious task, but, it would make using this lib so much easier. 

Thanks

**Comment by vayan** [comment]
Hey! It's auto generated from https://ldtk.io/api/#Python so I probably won't add documentation in it. 
But you can find some doc here https://ldtk.io/docs/game-dev/json-overview/

**Comment by ghost** [comment]
Got it, thanks!
